name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract InstaX ZIP
        run: |
          unzip -o InstaX-main.zip -d project

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.3.1"

      - name: Build Debug APK
        working-directory: project/InstaX-main
        run: |
          gradle assembleDebug --no-daemon

      - name: Find APK
        run: |
          find project -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: InstaX-APK
          path: project/InstaX-main/app/build/outputs/apk/debug/*.apk
