name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project
        run: |
          unzip -o InstaX-main.zip
          shopt -s dotglob
          mv InstaX-main/*.
          rm -rf InstaX-main InstaX-main.zip
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build APK
        run: |
          chmod +x gradlew
         ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: InstaX-APK
          path: app/build/outputs/apk/debug/*.apk
